language: python
python:
  - "2.7"
# command to install dependencies

before_install:
  - sudo apt-get update

  ### install blast+
  # this fails often with connection errors
  - sudo apt-get install ncbi-blast+


  #### install papara
  - wget 'https://sco.h-its.org/exelixis/resource/download/software/papara_nt-2.5-static_x86_64.tar.gz'
  - gunzip  -cd papara_nt-2.5-static_x86_64.tar.gz 
  - export PATH="$PATH:$(pwd)"


# command to run tests
script:
  - papara
