language: python
python:
  - "2.7"
# command to install dependencies

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  #- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  #- chmod +x miniconda.sh
  #- ./miniconda.sh -b
  #- export PATH=/home/travis/miniconda/bin:$PATH

    #### install papara

  - wget 'https://sco.h-its.org/exelixis/resource/download/software/papara_nt-2.5-static_x86_64.tar.gz'
  - gunzip  -cd papara_nt-2.5-static_x86_64.tar.gz 
  - export PATH=$PATH:./


  ### install blastn

  #- wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.7.1+-x64-linux.tar.gz
  
  #- tar -xvzf ncbi-blast-2.7.1+-x64-linux.tar.gz
  #- export PATH=$PATH:./ncbi-blast-2.7.1+
  




install:
  - sudo apt-get update
  - sudo apt-get install ncbi-blast+

  - pip install --quiet -r requirements.txt
  - pip install --quiet . 

  ##### to use RAXML we need conda
  # Here we just install Miniconda, which you shouldn't have to change.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install --yes bioconda raxml
  - python setup.py install



# command to run tests
script:


  - wget 'https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz'
  - gunzip  -cd taxdump.tar.gz | (tar xvf - names.dmp nodes.dmp)
  - mv *.dmp tests/data/
  - echo 'no' | python tests/testfilesetup.py
  - py.test tests/ --setup-only


